# Generated by Django 5.1.14 on 2026-01-18 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patterns/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, default='Untitled Pattern', max_length=255)),
                ('size', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
